### ISSUE TITLE
Order items is empty

### ISSUE THREAD

**Issue by armandino** [Mobe91/instancio-jpa#1]
**Describe the bug**
@Mobe91 thanks for creating this project! :)

I was playing around with creating an `Order` and noticed that `OrderItem` collection is not getting populated:

```java
    @Test
    void testOrder() {
        // Given
        Order order = Instancio.of(jpaModel(Order.class, emf.getMetamodel()).build()).create();

        // When
        doInTransaction(() -> {
            entityGraphPersister.persist(order);
        });

        // Then
        Order actualOrder = doInTransaction(() -> entityManager.find(Order.class, order.getId()));
        assertThat(actualOrder).isNotNull();

        assertThat(actualOrder.getOrderItems())
                .isNotEmpty() // fails: actual is empty
                .allSatisfy(item -> assertThat(item).isNotNull());
    }
```

Not sure if a bug or I missed some required setup.

**Expected result**
`getOrderItems()` should return a non-empty collection

**Actual result**
`getOrderItems()` is empty

**Link to a minimal sample project reproducing the issue or runnable sample code**

https://github.com/Mobe91/instancio-jpa/blob/c3a5cfaba90dd087b07a015b287a612762746eae/testsuite/javax/src/test/java/com/mobecker/instancio/jpa/testsuite/EntityGraphPersisterTest.java#L85

- Java version: `18`
- Instancio version: `2.16.1`
- Instancio-jpa version: `1.0.0-SNAPSHOT`

**Comment by Mobe91** [comment]
Hi @armandino! 🙂

Thanks for creating the first issue on this project! 😄

What you describe is actually expected behavior. If no maxDepth is specified the extension uses a computed _minimal_ value that is required for yielding a persistable entity graph. In this case, `Order` has no other required associations and therefore the computed maxDepth will be 1. That's the reason why the `orderItems` are not populated.

You can override the maxDepth to a value >= 2 to have the orderItems initialized.

```java
    @Test
    void testOrder() {
        // Given
        Order order = Instancio.of(jpaModel(Order.class, emf.getMetamodel()).build()).withMaxDepth(2).create();

        // When
        doInTransaction(() -> {
            entityGraphPersister.persist(order);
        });

        // Then
        Order actualOrder = doInTransaction(() -> entityManager.find(Order.class, order.getId()));
        assertThat(actualOrder).isNotNull();

        assertThat(actualOrder.getOrderItems())
            .isNotEmpty()
            .allSatisfy(item -> assertThat(item).isNotNull());
    }
```
Note that above test will still fail when persisting the entity because the unidirectional `@OneToMany` misses a `@JoinColumn` annotation.
Changing the `Order` entity as follows will make it work:
```java
    @Entity
    @Table(name = "service_order")
    public static class Order extends AbstractEntity {

        private Set<OrderItem> orderItems = new HashSet<>(0);

        @Id
        @GeneratedValue
        @Override
        public Long getId() {
            return super.getId();
        }

        @OneToMany
        @JoinColumn(name="order_id")
        public Set<OrderItem> getOrderItems() {
            return orderItems;
        }

        public void setOrderItems(Set<OrderItem> orderItems) {
            this.orderItems = orderItems;
        }
    }
```

**Comment by armandino** [comment]
Thanks @Mobe91! User error, as i suspected :)
